test:
  consumer_api_key: 52GglzrtEIL82YNiFkDKwNSKR"
  consumer_api_secret: Sg1gsKXx4dfg50zg0S8OGMG9aq8hrW9aObMO3480TGUEVmps2q
  oauth_token: 250190173-nLwaMZhHlzJQ0mKWslHRwlIXWWyra0jANdxwogWW
  oauth_token_secret: eCvvdEPAdPieBsysPIJ2XCqGLsM9X2guwgOBzHEAj2szf

development:
  consumer_api_key: 52GglzrtEIL82YNiFkDKwNSKR
  consumer_api_secret: Sg1gsKXx4dfg50zg0S8OGMG9aq8hrW9aObMO3480TGUEVmps2q
